# Generated by Django 5.2.4 on 2025-09-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_parent'),
        ('comments', '0002_remove_comment_post_comment_content_type_and_more'),
    ]

    operations = [
    ]
