# Generated by Django 5.2.4 on 2025-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_groupchat_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
