# Generated by Django 5.2.4 on 2025-09-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_repost_savedpost'),
        ('posts', '0006_alter_like_unique_together'),
    ]

    operations = [
    ]
