# Generated by Django 5.2.4 on 2025-09-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_block'),
        ('users', '0002_customuser_is_banned'),
    ]

    operations = [
    ]
